# copy this tile to "reddit.yaml" or any name of your choice (must not start with _)
# and enter your correct values.
reddit:
  client_id: "CLIENT_ID"
  client_secret: "CLIENT_SECRET"
  user_agent: "user agent to be sent to reddit, might have to contain your reddit handle but probably not idk"